
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr  1 2025 17:44:25 IST (Apr  1 2025 12:14:25 UTC)

// Verification Directory fv/lock 

module lock(clock, reset, x, ready, unlock, error);
  input clock, reset, x;
  output ready, unlock, error;
  wire clock, reset, x;
  wire ready, unlock, error;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_13, n_14, n_15, n_16, n_19;
  wire n_20, n_21, n_22, n_23, n_36, n_37;
  nd02d1 g335__2398(.A1 (n_20), .A2 (n_6), .ZN (n_22));
  nd02d1 g333__5107(.A1 (n_20), .A2 (n_10), .ZN (n_21));
  oai221d1 g338__6260(.A (n_9), .B1 (n_13), .B2 (state[2]), .C1 (n_15),
       .C2 (n_11), .ZN (n_19));
  aoi21d1 g339__5526(.A (n_16), .B1 (n_15), .B2 (state[1]), .ZN (n_20));
  nr03d1 g345__6783(.A1 (n_2), .A2 (n_3), .A3 (n_13), .ZN (n_14));
  aon211d1 g336__1617(.A (x), .B (n_0), .C1 (state[0]), .C2 (state[1]),
       .ZN (n_10));
  nr02d1 g344__2802(.A1 (x), .A2 (n_9), .ZN (n_16));
  nr02d1 g342__5122(.A1 (n_4), .A2 (n_13), .ZN (n_7));
  aoi22d1 g347__8246(.A1 (n_5), .A2 (state[0]), .B1 (x), .B2
       (state[1]), .ZN (n_6));
  inv0d0 g348(.I (n_4), .ZN (n_15));
  nd02d1 g349__7098(.A1 (n_3), .A2 (n_2), .ZN (n_4));
  nd02d1 g350__6131(.A1 (n_5), .A2 (state[2]), .ZN (n_9));
  an03d0 g346__1881(.A1 (n_3), .A2 (state[1]), .A3 (state[2]), .Z
       (n_1));
  oai21d1 g343__5115(.A (state[2]), .B1 (state[0]), .B2 (state[1]), .ZN
       (n_0));
  nd02d1 g351__7482(.A1 (n_11), .A2 (state[1]), .ZN (n_13));
  inv0d0 g352(.I (reset), .ZN (n_23));
  inv0d0 g355(.I (x), .ZN (n_11));
  bufbdk drc_bufs(.I (n_36), .Z (ready));
  bufbdk drc_bufs362(.I (n_37), .Z (error));
  bufbdk drc_bufs365(.I (n_1), .Z (unlock));
  dfcrb1 \state_reg[1] (.CDN (n_23), .CP (clock), .D (n_22), .Q
       (state[1]), .QN (n_5));
  dfcrb1 \state_reg[0] (.CDN (n_23), .CP (clock), .D (n_21), .Q
       (state[0]), .QN (n_3));
  dfcrb1 \state_reg[2] (.CDN (n_23), .CP (clock), .D (n_19), .Q
       (state[2]), .QN (n_2));
  aor31d1 g2(.A (n_14), .B1 (n_15), .B2 (n_11), .B3 (n_5), .Z (n_36));
  aor311d1 g374(.A (n_16), .B (n_7), .C1 (n_9), .C2 (x), .C3
       (state[0]), .Z (n_37));
endmodule

