
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 21 2025 11:33:46 IST (Mar 21 2025 06:03:46 UTC)

// Verification Directory fv/db_fsm 

module db_fsm(clk_pad, rst_pad, sw_pad, db_pad);
  input clk_pad, rst_pad, sw_pad;
  output db_pad;

  wire clk, rst, sw;
  wire db;
  wire [2:0] state_reg;
  wire [18:0] q_reg;
  wire [18:0] q_next;
  wire inc_add_22_21_n_0, inc_add_22_21_n_2, inc_add_22_21_n_4,
       inc_add_22_21_n_6, inc_add_22_21_n_8, inc_add_22_21_n_10,
       inc_add_22_21_n_12, inc_add_22_21_n_14;
  wire inc_add_22_21_n_16, inc_add_22_21_n_18, inc_add_22_21_n_20,
       inc_add_22_21_n_22, inc_add_22_21_n_24, inc_add_22_21_n_26,
       inc_add_22_21_n_28, inc_add_22_21_n_30;
  wire inc_add_22_21_n_32, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18;
  inv0d0 g822(.I (rst), .ZN (n_18));
  dfcrq1 \state_reg_reg[2] (.CDN (n_18), .CP (clk), .D (n_16), .Q (db));
  mx02d1 g1104__2398(.I0 (db), .I1 (sw), .S (n_12), .Z (n_16));
  oan211d1 g1105__5107(.A (n_2), .B (n_13), .C1 (n_11), .C2
       (state_reg[1]), .ZN (n_15));
  dfcrq1 \state_reg_reg[0] (.CDN (n_18), .CP (clk), .D (n_14), .Q
       (state_reg[0]));
  oan211d1 g1107__6260(.A (n_2), .B (n_10), .C1 (n_9), .C2
       (state_reg[0]), .ZN (n_14));
  nd02d1 g1108__4319(.A1 (n_11), .A2 (state_reg[1]), .ZN (n_13));
  nr02d1 g1109__8428(.A1 (n_0), .A2 (n_11), .ZN (n_12));
  nd02d1 g1110__5526(.A1 (n_8), .A2 (state_reg[0]), .ZN (n_11));
  oai21d1 g1111__6783(.A (n_9), .B1 (n_0), .B2 (state_reg[0]), .ZN
       (n_10));
  inv0d0 g1112(.I (n_8), .ZN (n_9));
  nr04d1 g1113__3680(.A1 (q_reg[0]), .A2 (q_reg[18]), .A3 (q_reg[14]),
       .A4 (n_7), .ZN (n_8));
  or04d0 g1114__1617(.A1 (n_6), .A2 (q_reg[13]), .A3 (q_reg[12]), .A4
       (q_reg[11]), .Z (n_7));
  or04d0 g1115__2802(.A1 (n_5), .A2 (q_reg[8]), .A3 (q_reg[9]), .A4
       (q_reg[10]), .Z (n_6));
  or04d0 g1116__1705(.A1 (n_4), .A2 (q_reg[15]), .A3 (q_reg[16]), .A4
       (q_reg[17]), .Z (n_5));
  or04d0 g1117__5122(.A1 (n_3), .A2 (q_reg[1]), .A3 (q_reg[2]), .A4
       (q_reg[6]), .Z (n_4));
  or04d0 g1118__8246(.A1 (q_reg[5]), .A2 (q_reg[7]), .A3 (q_reg[4]),
       .A4 (q_reg[3]), .Z (n_3));
  aoim22d1 g1119__7098(.A1 (db), .A2 (n_1), .B1 (db), .B2 (n_1), .Z
       (n_2));
  dfcrq1 \q_reg_reg[8] (.CDN (n_18), .CP (clk), .D (q_next[8]), .Q
       (q_reg[8]));
  dfcrq1 \q_reg_reg[1] (.CDN (n_18), .CP (clk), .D (q_next[1]), .Q
       (q_reg[1]));
  dfcrq1 \q_reg_reg[2] (.CDN (n_18), .CP (clk), .D (q_next[2]), .Q
       (q_reg[2]));
  dfcrq1 \q_reg_reg[3] (.CDN (n_18), .CP (clk), .D (q_next[3]), .Q
       (q_reg[3]));
  dfcrq1 \q_reg_reg[4] (.CDN (n_18), .CP (clk), .D (q_next[4]), .Q
       (q_reg[4]));
  dfcrq1 \q_reg_reg[17] (.CDN (n_18), .CP (clk), .D (q_next[17]), .Q
       (q_reg[17]));
  dfcrq1 \q_reg_reg[7] (.CDN (n_18), .CP (clk), .D (q_next[7]), .Q
       (q_reg[7]));
  dfcrq1 \q_reg_reg[6] (.CDN (n_18), .CP (clk), .D (q_next[6]), .Q
       (q_reg[6]));
  dfcrq1 \q_reg_reg[9] (.CDN (n_18), .CP (clk), .D (q_next[9]), .Q
       (q_reg[9]));
  dfcrq1 \q_reg_reg[10] (.CDN (n_18), .CP (clk), .D (q_next[10]), .Q
       (q_reg[10]));
  dfcrq1 \q_reg_reg[11] (.CDN (n_18), .CP (clk), .D (q_next[11]), .Q
       (q_reg[11]));
  dfcrq1 \q_reg_reg[12] (.CDN (n_18), .CP (clk), .D (q_next[12]), .Q
       (q_reg[12]));
  dfcrq1 \q_reg_reg[14] (.CDN (n_18), .CP (clk), .D (q_next[14]), .Q
       (q_reg[14]));
  dfcrq1 \q_reg_reg[15] (.CDN (n_18), .CP (clk), .D (q_next[15]), .Q
       (q_reg[15]));
  dfcrq1 \q_reg_reg[16] (.CDN (n_18), .CP (clk), .D (q_next[16]), .Q
       (q_reg[16]));
  dfcrq1 \q_reg_reg[5] (.CDN (n_18), .CP (clk), .D (q_next[5]), .Q
       (q_reg[5]));
  dfcrq1 \q_reg_reg[18] (.CDN (n_18), .CP (clk), .D (q_next[18]), .Q
       (q_reg[18]));
  dfcrq1 \q_reg_reg[13] (.CDN (n_18), .CP (clk), .D (q_next[13]), .Q
       (q_reg[13]));
  inv0d0 g1139(.I (sw), .ZN (n_1));
  xr02d1 inc_add_22_21_g306__6131(.A1 (inc_add_22_21_n_32), .A2
       (q_reg[18]), .Z (q_next[18]));
  ah01d1 inc_add_22_21_g307__1881(.A (inc_add_22_21_n_30), .B
       (q_reg[17]), .CO (inc_add_22_21_n_32), .S (q_next[17]));
  ah01d1 inc_add_22_21_g308__5115(.A (inc_add_22_21_n_28), .B
       (q_reg[16]), .CO (inc_add_22_21_n_30), .S (q_next[16]));
  ah01d1 inc_add_22_21_g309__7482(.A (inc_add_22_21_n_26), .B
       (q_reg[15]), .CO (inc_add_22_21_n_28), .S (q_next[15]));
  ah01d1 inc_add_22_21_g310__4733(.A (inc_add_22_21_n_24), .B
       (q_reg[14]), .CO (inc_add_22_21_n_26), .S (q_next[14]));
  ah01d1 inc_add_22_21_g311__6161(.A (inc_add_22_21_n_22), .B
       (q_reg[13]), .CO (inc_add_22_21_n_24), .S (q_next[13]));
  ah01d1 inc_add_22_21_g312__9315(.A (inc_add_22_21_n_20), .B
       (q_reg[12]), .CO (inc_add_22_21_n_22), .S (q_next[12]));
  ah01d1 inc_add_22_21_g313__9945(.A (inc_add_22_21_n_18), .B
       (q_reg[11]), .CO (inc_add_22_21_n_20), .S (q_next[11]));
  ah01d1 inc_add_22_21_g314__2883(.A (inc_add_22_21_n_16), .B
       (q_reg[10]), .CO (inc_add_22_21_n_18), .S (q_next[10]));
  ah01d1 inc_add_22_21_g315__2346(.A (inc_add_22_21_n_14), .B
       (q_reg[9]), .CO (inc_add_22_21_n_16), .S (q_next[9]));
  ah01d1 inc_add_22_21_g316__1666(.A (inc_add_22_21_n_12), .B
       (q_reg[8]), .CO (inc_add_22_21_n_14), .S (q_next[8]));
  ah01d1 inc_add_22_21_g317__7410(.A (inc_add_22_21_n_10), .B
       (q_reg[7]), .CO (inc_add_22_21_n_12), .S (q_next[7]));
  ah01d1 inc_add_22_21_g318__6417(.A (inc_add_22_21_n_8), .B
       (q_reg[6]), .CO (inc_add_22_21_n_10), .S (q_next[6]));
  ah01d1 inc_add_22_21_g319__5477(.A (inc_add_22_21_n_6), .B
       (q_reg[5]), .CO (inc_add_22_21_n_8), .S (q_next[5]));
  ah01d1 inc_add_22_21_g320__2398(.A (inc_add_22_21_n_4), .B
       (q_reg[4]), .CO (inc_add_22_21_n_6), .S (q_next[4]));
  ah01d1 inc_add_22_21_g321__5107(.A (inc_add_22_21_n_2), .B
       (q_reg[3]), .CO (inc_add_22_21_n_4), .S (q_next[3]));
  ah01d1 inc_add_22_21_g322__6260(.A (inc_add_22_21_n_0), .B
       (q_reg[2]), .CO (inc_add_22_21_n_2), .S (q_next[2]));
  ah01d1 inc_add_22_21_g323__4319(.A (q_reg[1]), .B (q_reg[0]), .CO
       (inc_add_22_21_n_0), .S (q_next[1]));
  dfcrb1 \state_reg_reg[1] (.CDN (n_18), .CP (clk), .D (n_15), .Q
       (state_reg[1]), .QN (n_0));
  dfcrb1 \q_reg_reg[0] (.CDN (n_18), .CP (clk), .D (n_17), .Q
       (q_reg[0]), .QN (n_17));


//  pc3c01 pc3c01_1(.CCLK (clock), .CP (clk));
//  pc3d01 pc3d01_1(.PAD (clk_pad), .CIN (clock));

//  pc3d01 pc3d01_2(.PAD (rst_pad), .CIN (rst));

//  pc3d01 pc3d01_3(.PAD (sw_pad), .CIN (sw));
  
//  pc3o05 pc3o05_1(.I (db), .PAD (db_pad));

//  pvdi   pvdi_VDD_CORE_1   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
//  pv0i   pv0i_VSS_CORE_1   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
//  pvda   pvda_VDDO_CORE_1  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
//  pv0a   pv0a_VSSO_CORE_1  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));

//  pvdi   pvdi_VDD_CORE_2   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
//  pv0i   pv0i_VSS_CORE_2   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
//  pvda   pvda_VDDO_CORE_2  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
//  pv0a   pv0a_VSSO_CORE_2  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));

endmodule

