
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 27 2025 19:34:27 IST (Mar 27 2025 14:04:27 UTC)

// Verification Directory fv/lock 

module lock(clock, reset, x, ready, unlock, error);
  input clock, reset, x;
  output ready, unlock, error;
  wire clock, reset, x;
  wire ready, unlock, error;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_11, n_12, n_13, n_15, n_17, n_18;
  wire n_21, n_22, n_23, n_25, n_35, n_37, n_38, n_39;
  OAI2BB1XL g360(.A0N (n_7), .A1N (x), .B0 (n_21), .Y (n_23));
  NAND2XL g362(.A (n_3), .B (n_21), .Y (n_22));
  OAI221X1 g363(.A0 (state[2]), .A1 (n_11), .B0 (n_17), .B1 (n_4), .C0
       (n_15), .Y (n_18));
  AOI21X1 g369(.A0 (state[1]), .A1 (n_17), .B0 (n_13), .Y (n_21));
  NOR3X1 g370(.A (n_0), .B (n_5), .C (n_11), .Y (n_12));
  NOR3BX1 g372(.AN (n_17), .B (state[1]), .C (x), .Y (n_9));
  NAND2BXL g373(.AN (n_11), .B (n_17), .Y (n_8));
  OAI211XL g365(.A0 (state[0]), .A1 (state[1]), .B0 (state[2]), .C0
       (n_2), .Y (n_7));
  NOR2XL g376(.A (n_15), .B (x), .Y (n_13));
  NOR2XL g379(.A (state[0]), .B (n_5), .Y (n_6));
  NAND2XL g380(.A (state[1]), .B (n_4), .Y (n_11));
  MXI2XL g367(.A (state[0]), .B (x), .S0 (state[1]), .Y (n_3));
  NAND2XL g381(.A (state[2]), .B (n_1), .Y (n_15));
  NAND2XL g377(.A (state[0]), .B (state[1]), .Y (n_2));
  NOR2XL g378(.A (state[0]), .B (state[2]), .Y (n_17));
  CLKINVX1 g383(.A (x), .Y (n_4));
  INVXL g382(.A (reset), .Y (n_25));
  CLKINVX20 drc_buf_sp(.A (n_35), .Y (ready));
  CLKINVX20 drc_buf_sp391(.A (n_39), .Y (error));
  CLKINVX20 drc_buf_sp393(.A (n_37), .Y (unlock));
  DFFRX1 \state_reg[1] (.RN (n_25), .CK (clock), .D (n_22), .Q
       (state[1]), .QN (n_1));
  DFFRX1 \state_reg[0] (.RN (n_25), .CK (clock), .D (n_23), .Q
       (state[0]), .QN (n_0));
  DFFRX1 \state_reg[2] (.RN (n_25), .CK (clock), .D (n_18), .Q
       (state[2]), .QN (n_5));
  NOR2XL g2(.A (n_9), .B (n_12), .Y (n_35));
  NAND2XL g402(.A (state[1]), .B (n_6), .Y (n_37));
  NAND2BX1 g403(.AN (n_13), .B (n_8), .Y (n_38));
  AOI31X1 g404(.A0 (state[0]), .A1 (n_15), .A2 (x), .B0 (n_38), .Y
       (n_39));
endmodule

