
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb 27 2025 17:06:54 IST (Feb 27 2025 11:36:54 UTC)

// Verification Directory fv/db_fsm 
`timescale 1 ns/10 ps
module db_fsm(clk, rst, sw, db);
  input clk, rst, sw;
  output db;
  wire clk, rst, sw;
  wire db;
  wire [2:0] state_reg;
  wire [18:0] q_reg;
  wire [18:0] q_next;
  wire inc_add_22_21_n_0, inc_add_22_21_n_1, inc_add_22_21_n_2,
       inc_add_22_21_n_3, inc_add_22_21_n_4, inc_add_22_21_n_6,
       inc_add_22_21_n_8, inc_add_22_21_n_10;
  wire inc_add_22_21_n_12, inc_add_22_21_n_13, inc_add_22_21_n_15,
       inc_add_22_21_n_17, inc_add_22_21_n_19, inc_add_22_21_n_20,
       inc_add_22_21_n_22, inc_add_22_21_n_24;
  wire inc_add_22_21_n_27, inc_add_22_21_n_28, inc_add_22_21_n_30,
       inc_add_22_21_n_31, inc_add_22_21_n_33, inc_add_22_21_n_35,
       inc_add_22_21_n_37, inc_add_22_21_n_38;
  wire inc_add_22_21_n_40, inc_add_22_21_n_41, inc_add_22_21_n_43, n_0,
       n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17;
  INVXL g468(.A (rst), .Y (n_17));
  SDFFRHQX1 \state_reg_reg[2] (.RN (n_17), .CK (clk), .D (sw), .SI
       (db), .SE (n_11), .Q (db));
  DFFRHQX1 \state_reg_reg[1] (.RN (n_17), .CK (clk), .D (n_16), .Q
       (state_reg[1]));
  NOR2XL g1061(.A (n_3), .B (n_14), .Y (n_16));
  DFFRHQX1 \state_reg_reg[0] (.RN (n_17), .CK (clk), .D (n_15), .Q
       (state_reg[0]));
  NOR2XL g1063(.A (n_3), .B (n_12), .Y (n_15));
  AOI21XL g1064(.A0 (state_reg[1]), .A1 (n_10), .B0 (n_13), .Y (n_14));
  NOR2XL g1065(.A (state_reg[1]), .B (n_10), .Y (n_13));
  MX2X1 g1066(.A (n_1), .B (state_reg[0]), .S0 (n_9), .Y (n_12));
  NAND2BXL g1067(.AN (n_10), .B (state_reg[1]), .Y (n_11));
  NAND2XL g1068(.A (state_reg[0]), .B (n_9), .Y (n_10));
  NOR4BXL g1069(.AN (n_8), .B (q_reg[2]), .C (q_reg[1]), .D (q_reg[6]),
       .Y (n_9));
  NOR4BXL g1070(.AN (n_7), .B (q_reg[5]), .C (q_reg[4]), .D (q_reg[3]),
       .Y (n_8));
  NOR4BXL g1071(.AN (n_6), .B (q_reg[10]), .C (q_reg[15]), .D
       (q_reg[0]), .Y (n_7));
  NOR4BXL g1072(.AN (n_5), .B (q_reg[16]), .C (q_reg[17]), .D
       (q_reg[18]), .Y (n_6));
  NOR4BXL g1073(.AN (n_4), .B (q_reg[13]), .C (q_reg[14]), .D
       (q_reg[12]), .Y (n_5));
  NOR4XL g1074(.A (q_reg[11]), .B (q_reg[7]), .C (q_reg[8]), .D
       (q_reg[9]), .Y (n_4));
  OAI21XL g1075(.A0 (sw), .A1 (db), .B0 (n_2), .Y (n_3));
  DFFRHQX1 \q_reg_reg[9] (.RN (n_17), .CK (clk), .D (q_next[9]), .Q
       (q_reg[9]));
  DFFRHQX1 \q_reg_reg[3] (.RN (n_17), .CK (clk), .D (q_next[3]), .Q
       (q_reg[3]));
  DFFRHQX1 \q_reg_reg[4] (.RN (n_17), .CK (clk), .D (q_next[4]), .Q
       (q_reg[4]));
  DFFRHQX1 \q_reg_reg[17] (.RN (n_17), .CK (clk), .D (q_next[17]), .Q
       (q_reg[17]));
  DFFRHQX1 \q_reg_reg[7] (.RN (n_17), .CK (clk), .D (q_next[7]), .Q
       (q_reg[7]));
  DFFRHQX1 \q_reg_reg[8] (.RN (n_17), .CK (clk), .D (q_next[8]), .Q
       (q_reg[8]));
  DFFRHQX1 \q_reg_reg[1] (.RN (n_17), .CK (clk), .D (q_next[1]), .Q
       (q_reg[1]));
  NAND2XL g1086(.A (sw), .B (db), .Y (n_2));
  NOR2BXL g1087(.AN (state_reg[1]), .B (state_reg[0]), .Y (n_1));
  DFFRHQX1 \q_reg_reg[12] (.RN (n_17), .CK (clk), .D (q_next[12]), .Q
       (q_reg[12]));
  DFFRHQX1 \q_reg_reg[15] (.RN (n_17), .CK (clk), .D (q_next[15]), .Q
       (q_reg[15]));
  DFFRHQX1 \q_reg_reg[5] (.RN (n_17), .CK (clk), .D (q_next[5]), .Q
       (q_reg[5]));
  DFFRHQX1 \q_reg_reg[18] (.RN (n_17), .CK (clk), .D (q_next[18]), .Q
       (q_reg[18]));
  DFFRHQX1 \q_reg_reg[13] (.RN (n_17), .CK (clk), .D (q_next[13]), .Q
       (q_reg[13]));
  DFFRHQX1 \q_reg_reg[16] (.RN (n_17), .CK (clk), .D (q_next[16]), .Q
       (q_reg[16]));
  DFFRHQX1 \q_reg_reg[11] (.RN (n_17), .CK (clk), .D (q_next[11]), .Q
       (q_reg[11]));
  OAI21XL inc_add_22_21_g229(.A0 (q_reg[18]), .A1 (inc_add_22_21_n_41),
       .B0 (inc_add_22_21_n_43), .Y (q_next[18]));
  NAND2XL inc_add_22_21_g230(.A (q_reg[18]), .B (inc_add_22_21_n_41),
       .Y (inc_add_22_21_n_43));
  OAI21XL inc_add_22_21_g231(.A0 (q_reg[17]), .A1 (inc_add_22_21_n_37),
       .B0 (inc_add_22_21_n_40), .Y (q_next[17]));
  NAND2BXL inc_add_22_21_g232(.AN (inc_add_22_21_n_37), .B (q_reg[17]),
       .Y (inc_add_22_21_n_41));
  NAND2XL inc_add_22_21_g233(.A (q_reg[17]), .B (inc_add_22_21_n_37),
       .Y (inc_add_22_21_n_40));
  OAI21XL inc_add_22_21_g234(.A0 (q_reg[16]), .A1 (inc_add_22_21_n_35),
       .B0 (inc_add_22_21_n_38), .Y (q_next[16]));
  NAND2XL inc_add_22_21_g235(.A (q_reg[16]), .B (inc_add_22_21_n_35),
       .Y (inc_add_22_21_n_38));
  NAND2BXL inc_add_22_21_g236(.AN (inc_add_22_21_n_35), .B (q_reg[16]),
       .Y (inc_add_22_21_n_37));
  OA21X1 inc_add_22_21_g237(.A0 (q_reg[15]), .A1 (inc_add_22_21_n_33),
       .B0 (inc_add_22_21_n_35), .Y (q_next[15]));
  NAND2XL inc_add_22_21_g238(.A (q_reg[15]), .B (inc_add_22_21_n_33),
       .Y (inc_add_22_21_n_35));
  AOI21XL inc_add_22_21_g239(.A0 (inc_add_22_21_n_0), .A1
       (inc_add_22_21_n_31), .B0 (inc_add_22_21_n_33), .Y (q_next[14]));
  NOR2XL inc_add_22_21_g240(.A (inc_add_22_21_n_0), .B
       (inc_add_22_21_n_31), .Y (inc_add_22_21_n_33));
  OAI21XL inc_add_22_21_g241(.A0 (q_reg[13]), .A1 (inc_add_22_21_n_28),
       .B0 (inc_add_22_21_n_30), .Y (q_next[13]));
  NAND2BXL inc_add_22_21_g242(.AN (inc_add_22_21_n_28), .B (q_reg[13]),
       .Y (inc_add_22_21_n_31));
  NAND2XL inc_add_22_21_g243(.A (q_reg[13]), .B (inc_add_22_21_n_28),
       .Y (inc_add_22_21_n_30));
  OA21X1 inc_add_22_21_g244(.A0 (q_reg[12]), .A1 (inc_add_22_21_n_27),
       .B0 (inc_add_22_21_n_28), .Y (q_next[12]));
  NAND2XL inc_add_22_21_g245(.A (q_reg[12]), .B (inc_add_22_21_n_27),
       .Y (inc_add_22_21_n_28));
  ADDHX1 inc_add_22_21_g246(.A (q_reg[11]), .B (inc_add_22_21_n_24),
       .CO (inc_add_22_21_n_27), .S (q_next[11]));
  AOI21XL inc_add_22_21_g247(.A0 (inc_add_22_21_n_1), .A1
       (inc_add_22_21_n_22), .B0 (inc_add_22_21_n_24), .Y (q_next[10]));
  NOR2XL inc_add_22_21_g248(.A (inc_add_22_21_n_1), .B
       (inc_add_22_21_n_22), .Y (inc_add_22_21_n_24));
  OA21X1 inc_add_22_21_g249(.A0 (q_reg[9]), .A1 (inc_add_22_21_n_20),
       .B0 (inc_add_22_21_n_22), .Y (q_next[9]));
  NAND2XL inc_add_22_21_g250(.A (q_reg[9]), .B (inc_add_22_21_n_20), .Y
       (inc_add_22_21_n_22));
  OAI21XL inc_add_22_21_g251(.A0 (q_reg[8]), .A1 (inc_add_22_21_n_17),
       .B0 (inc_add_22_21_n_19), .Y (q_next[8]));
  NOR2BXL inc_add_22_21_g252(.AN (q_reg[8]), .B (inc_add_22_21_n_17),
       .Y (inc_add_22_21_n_20));
  NAND2XL inc_add_22_21_g253(.A (q_reg[8]), .B (inc_add_22_21_n_17), .Y
       (inc_add_22_21_n_19));
  OA21X1 inc_add_22_21_g254(.A0 (q_reg[7]), .A1 (inc_add_22_21_n_15),
       .B0 (inc_add_22_21_n_17), .Y (q_next[7]));
  NAND2XL inc_add_22_21_g255(.A (q_reg[7]), .B (inc_add_22_21_n_15), .Y
       (inc_add_22_21_n_17));
  AOI21XL inc_add_22_21_g256(.A0 (inc_add_22_21_n_3), .A1
       (inc_add_22_21_n_12), .B0 (inc_add_22_21_n_15), .Y (q_next[6]));
  NOR2XL inc_add_22_21_g257(.A (inc_add_22_21_n_3), .B
       (inc_add_22_21_n_12), .Y (inc_add_22_21_n_15));
  OAI21XL inc_add_22_21_g258(.A0 (q_reg[5]), .A1 (inc_add_22_21_n_10),
       .B0 (inc_add_22_21_n_13), .Y (q_next[5]));
  NAND2XL inc_add_22_21_g259(.A (q_reg[5]), .B (inc_add_22_21_n_10), .Y
       (inc_add_22_21_n_13));
  NAND2BXL inc_add_22_21_g260(.AN (inc_add_22_21_n_10), .B (q_reg[5]),
       .Y (inc_add_22_21_n_12));
  OA21X1 inc_add_22_21_g261(.A0 (q_reg[4]), .A1 (inc_add_22_21_n_8),
       .B0 (inc_add_22_21_n_10), .Y (q_next[4]));
  NAND2XL inc_add_22_21_g262(.A (q_reg[4]), .B (inc_add_22_21_n_8), .Y
       (inc_add_22_21_n_10));
  AOI2BB1XL inc_add_22_21_g263(.A0N (q_reg[3]), .A1N
       (inc_add_22_21_n_6), .B0 (inc_add_22_21_n_8), .Y (q_next[3]));
  AND2X1 inc_add_22_21_g264(.A (q_reg[3]), .B (inc_add_22_21_n_6), .Y
       (inc_add_22_21_n_8));
  AOI21XL inc_add_22_21_g265(.A0 (inc_add_22_21_n_2), .A1
       (inc_add_22_21_n_4), .B0 (inc_add_22_21_n_6), .Y (q_next[2]));
  NOR2XL inc_add_22_21_g266(.A (inc_add_22_21_n_2), .B
       (inc_add_22_21_n_4), .Y (inc_add_22_21_n_6));
  OA21X1 inc_add_22_21_g267(.A0 (q_reg[1]), .A1 (q_reg[0]), .B0
       (inc_add_22_21_n_4), .Y (q_next[1]));
  NAND2XL inc_add_22_21_g268(.A (q_reg[1]), .B (q_reg[0]), .Y
       (inc_add_22_21_n_4));
  DFFRX1 \q_reg_reg[0] (.RN (n_17), .CK (clk), .D (n_0), .Q (q_reg[0]),
       .QN (n_0));
  DFFRX1 \q_reg_reg[6] (.RN (n_17), .CK (clk), .D (q_next[6]), .Q
       (q_reg[6]), .QN (inc_add_22_21_n_3));
  DFFRX1 \q_reg_reg[2] (.RN (n_17), .CK (clk), .D (q_next[2]), .Q
       (q_reg[2]), .QN (inc_add_22_21_n_2));
  DFFRX1 \q_reg_reg[10] (.RN (n_17), .CK (clk), .D (q_next[10]), .Q
       (q_reg[10]), .QN (inc_add_22_21_n_1));
  DFFRX1 \q_reg_reg[14] (.RN (n_17), .CK (clk), .D (q_next[14]), .Q
       (q_reg[14]), .QN (inc_add_22_21_n_0));
endmodule

